### ISSUE TITLE
(Requirement) Create Custom Widget 

### ISSUE THREAD

**Issue by ShutUpChips15** [CodingGrounds/CS3035-Final-Project#10]
CheckBox Widget: One of our cards is a checklist so I'm thinking make a widget to manage adding and removing checkboxes. This will keep the code out of card details and check the requirements box

**Comment by ehtonay** [comment]
I think the cards themselves will count as the custom widget. We just need to make sure you can input custom information, which we will.handle with view 2 (clicking on the card brings up card details)

**Comment by jasonncleveland** [comment]
Completed in #28
